apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluentd
  namespace: logging
  labels:
    role: fluentd
spec:
  replicas: 1
  selector:
    matchLabels:
      role: fluentd
  template:
    metadata:
      labels:
        role: fluentd
    spec:
      containers:
        - name: nginx
          image: nginx:latest
