apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager
  namespace: monitoring
  labels:
    role: alertmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      role: alertmanager
  template:
    metadata:
      labels:
        role: alertmanager
    spec:
      containers:
        - name: nginx
          image: nginx:latest
