# This rule is not used by the project restlink itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the core.restlink.io.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: restlink
    app.kubernetes.io/managed-by: kustomize
  name: restarttrigger-editor-role
rules:
- apiGroups:
  - core.restlink.io
  resources:
  - restarttriggers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.restlink.io
  resources:
  - restarttriggers/status
  verbs:
  - get
