---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - core.restlink.io
  resources:
  - restarttriggers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.restlink.io
  resources:
  - restarttriggers/finalizers
  verbs:
  - update
- apiGroups:
  - core.restlink.io
  resources:
  - restarttriggers/status
  verbs:
  - get
  - patch
  - update
